spring:
  application:
    name: snapbill
  profiles:
    active: prod # ← This tells Spring to also load application-dev.yml

# Common settings (no secrets here)
server:
  port: 8080

jpa:
  hibernate:
    ddl-auto: validate